# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
gems: [jekyll-paginate]
gems: [jekyll-gallery-generator]
paginate: 5
paginate_path: "page:num"
#relative_permalinks: true

# Setup
title:            'Burning Waters'
tagline:          'A place'
description:      'A different kind of resort'
url:              https://burningwaters.github.io/
baseurl:          /

author:
  name:           'Addison Serendipity'

paginate:         5


